'use client'

import { useState } from 'react'
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { Loader2, Sparkles, FileText } from 'lucide-react'

interface PlanInitializationProps {
  projectId: string
  onPlanCreated: () => void
}

export function PlanInitialization({
  projectId,
  onPlanCreated,
}: PlanInitializationProps) {
  const [mode, setMode] = useState<'select' | 'ai' | 'manual'>('select')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  // Manual creation form state
  const [title, setTitle] = useState('Project Plan')
  const [description, setDescription] = useState('')

  const handleAIGeneration = async () => {
    setLoading(true)
    setError(null)

    try {
      // TODO: Implement AI plan generation endpoint
      // For now, create a basic plan
      const response = await fetch(`/api/projects/${projectId}/plan`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          title: 'AI Generated Plan',
          description: 'Plan generated by AI analysis',
          generate: true,
        }),
      })

      if (!response.ok) {
        const data = await response.json()
        throw new Error(data.error || 'Failed to generate plan')
      }

      onPlanCreated()
    } catch (err: any) {
      setError(err.message || 'Failed to generate plan')
    } finally {
      setLoading(false)
    }
  }

  const handleManualCreation = async () => {
    if (!title.trim()) {
      setError('Title is required')
      return
    }

    setLoading(true)
    setError(null)

    try {
      const response = await fetch(`/api/projects/${projectId}/plan`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          title: title.trim(),
          description: description.trim() || null,
        }),
      })

      if (!response.ok) {
        const data = await response.json()
        throw new Error(data.error || 'Failed to create plan')
      }

      onPlanCreated()
    } catch (err: any) {
      setError(err.message || 'Failed to create plan')
    } finally {
      setLoading(false)
    }
  }

  if (mode === 'select') {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Initialize Project Plan</CardTitle>
          <CardDescription>
            Create a plan for tracking your project progress
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          <div className="grid gap-3 md:grid-cols-2">
            <Card
              className="group cursor-pointer transition-all hover:border-primary/50 hover:shadow-md"
              onClick={() => setMode('ai')}
            >
              <CardHeader>
                <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 group-hover:bg-primary/20 transition-colors mb-2">
                  <Sparkles className="h-5 w-5 text-primary" />
                </div>
                <CardTitle className="flex items-center gap-2">AI Generation</CardTitle>
                <CardDescription>
                  Let AI analyze your repository and generate a plan automatically
                </CardDescription>
              </CardHeader>
            </Card>

            <Card
              className="group cursor-pointer transition-all hover:border-primary/50 hover:shadow-md"
              onClick={() => setMode('manual')}
            >
              <CardHeader>
                <div className="flex h-8 w-8 items-center justify-center rounded-md bg-primary/10 group-hover:bg-primary/20 transition-colors mb-1.5">
                  <FileText className="h-5 w-5 text-primary" />
                </div>
                <CardTitle className="flex items-center gap-2">Manual Creation</CardTitle>
                <CardDescription>
                  Create a plan manually and add steps yourself
                </CardDescription>
              </CardHeader>
            </Card>
          </div>
        </CardContent>
      </Card>
    )
  }

  if (mode === 'ai') {
    return (
      <Card>
        <CardHeader>
          <CardTitle>AI Plan Generation</CardTitle>
          <CardDescription>
            Analyzing your repository to generate a project plan
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          {error && (
            <div className="rounded-md bg-destructive/10 px-3 py-2 text-sm text-destructive border border-destructive/20">
              {error}
            </div>
          )}

          <div className="space-y-4">
            <p className="text-sm text-muted-foreground">
              Click the button below to generate a plan based on your repository structure and recent commits.
            </p>

            <div className="flex gap-2">
              <Button
                variant="outline"
                onClick={() => setMode('select')}
                disabled={loading}
              >
                Back
              </Button>
              <Button onClick={handleAIGeneration} disabled={loading}>
                {loading ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Generating...
                  </>
                ) : (
                  <>
                    <Sparkles className="mr-2 h-4 w-4" />
                    Generate Plan
                  </>
                )}
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>
    )
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>Create Plan Manually</CardTitle>
        <CardDescription>
          Enter the details for your project plan
        </CardDescription>
      </CardHeader>
        <CardContent className="space-y-3">
        {error && (
          <div className="rounded-md bg-destructive/10 px-3 py-2 text-sm text-destructive border border-destructive/20">
            {error}
          </div>
        )}

        <div className="space-y-2">
          <Label htmlFor="plan-title">Plan Title *</Label>
          <Input
            id="plan-title"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            placeholder="Project Plan"
          />
        </div>

        <div className="space-y-2">
          <Label htmlFor="plan-description">Description</Label>
          <Textarea
            id="plan-description"
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            placeholder="Optional description of the project plan"
            rows={4}
          />
        </div>

        <div className="flex gap-2">
          <Button
            variant="outline"
            onClick={() => setMode('select')}
            disabled={loading}
          >
            Back
          </Button>
          <Button onClick={handleManualCreation} disabled={loading}>
            {loading ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Creating...
              </>
            ) : (
              'Create Plan'
            )}
          </Button>
        </div>
      </CardContent>
    </Card>
  )
}


